In [5]:
import numpy
a = numpy.zeros(shape=(5,3,2))

In [6]:
print(a)

[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]


In [15]:
a[1][1][1]=1

In [16]:
a

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  1.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [17]:
a[0][0][0]=1

In [19]:
a

array([[[ 1.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  1.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [21]:
print(type(a))

<class 'numpy.ndarray'>


In [26]:
decompose = KruskalTensor(a.shape, rank=2, regularize=1e-6, 
                                  init='nvecs', X_data=a)

In [85]:
from ktensor import KruskalTensor

In [29]:
factors = decompose.U

In [35]:
print(factors[2])

Tensor("U_1/2/read:0", shape=(2, 2), dtype=float64)


In [1]:
import os
print os.listdir(os.getcwd())
for filename in os.listdir(os.getcwd()):
    print(filename)

cosine.txt
.DS_Store
shakespeare_president.pkl
kmeans_cluster.html
Tensor Decomposition for Malware Analysis.ipynb
TensorDecomposition_Sept12.ipynb
shakespeare_president
loss.log
A Jupyter Notebook - Tensor Decomposition for Malware Analysis.ipynb
.ipynb_checkpoints
notebook_heatmap.html


In [4]:
directory = "/Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president"

In [13]:
for filename in os.listdir(directory):
    print(filename)
    if filename == '.pkl':
        continue
    with open(directory+"/"+filename) as myfile:
        head = myfile.readlines(5)
    print(head)

JC.txt
['Julius Caesar\n']
1957-Eisenhower.txt
['The Price of Peace\n']
TNK.txt
['The Two Noble Kinsmen\n']
Tmp.txt
['The Tempest\n']
1881-Garfield.txt
['Fellow-Citizens:\n']
1905-Roosevelt.txt
['My fellow citizens, no people on earth have more cause to be thankful than ours, and this is said reverently, in no spirit of boastfulness in our own strength, but with gratitude to the Giver of Good who has blessed us with the conditions which have enabled us to achieve so large a measure of well-being and of happiness. To us as a people it has been granted to lay the foundations of our national life in a new continent. We are the heirs of the ages, and yet we have had to pay few of the penalties which in old countries are exacted by the dead hand of a bygone civilization. We have not been obliged to fight for our existence against any alien race; and yet our life has called for the vigor and effort without which the manlier and hardier virtues wither away. Under such conditions it would be o

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 837: invalid start byte

In [82]:
import numpy as np
tensor = np.zeros((98, 4000, 3))
pos = 0
document_cutoff_positions = []
doc_content = []
max_sentences = 3
max_matrix_height = 0
file_counter  = 0 
for file_name in os.listdir(directory):
            file_counter = file_counter + 1
            doc_content = []
            document_cutoff_positions.append(pos)
            with open(directory + "/" + file_name, "r", errors="ignore") as file:
                print("Reading %s" %directory + "/" + file_name)
                for line in file:
                    if len(line) > 2:
                        pos += 1
                        doc_content.append(line)
                    if pos - document_cutoff_positions[-1] >= max_sentences:
                        #doc_content.append("////////////////////////")
                        x = ("".join(doc_content))
                        l = (getWords(x))
                        le = int(len(l)/3)
                        for i in range(0,len(l)):
                            if i < le:
#                                 if l[i] not in large_dict:
#                                     large_dict[l[i]]=1
#                                     tensor[file_counter][i][0] = 1
#                                 else:
                                    word_id = dict_tensor[l[i]]
                                    tensor[file_counter][word_id][0] = tensor[file_counter][word_id][0] + 1
#                                     print(word_id)
#                                     print(tensor[file_counter][word_id][0])
#                                     break
                                #print(i,l[i],"Top 33%")
                            elif i < (2*le):
#                                 if l[i] not in large_dict:
#                                     large_dict[l[i]]=1
#                                     tensor[file_counter][i][1] = 1
#                                 else:
                                    word_id = dict_tensor[l[i]]
                                    tensor[file_counter][word_id][1] = tensor[file_counter][word_id][1] + 1
                                #print(i,l[i],"Top 66%")
                            else:
#                                 if l[i] not in large_dict:
#                                     large_dict[l[i]]=1
#                                     tensor[file_counter][i][2] = 1
#                                 else:
                                    word_id = dict_tensor[l[i]]
                                    tensor[file_counter][word_id][2] = tensor[file_counter][word_id][2] + 1
                                #print(i,l[i],"Top 100%")
                        break
                if max_matrix_height < pos - document_cutoff_positions[-1]:
                    max_matrix_height = pos - document_cutoff_positions[-1]
document_cutoff_positions.append(pos)
print(document_cutoff_positions)
print(doc_content)
x1 = vectorizer.fit_transform(doc_content)
matrix_length = len(vectorizer.get_feature_names())

Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/JC.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/1957-Eisenhower.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/TNK.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/Tmp.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/1881-Garfield.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/1905-Roosevelt.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/1985-Reagan.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/1913-Wilson.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/Cym.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/2Henry4.txt
Reading /Users/Phaniteja/desktop/RA/Ju

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(use_idf=False)

In [24]:
print(matrix_length)

2918


In [28]:
type(x1)

scipy.sparse.csr.csr_matrix

In [29]:
x1.shape

(382, 2918)

In [30]:
type(doc_content)

list

In [31]:
len(doc_content)

382

In [34]:
text1 ="Hello world! It's time for ROBO 2.0"

import re
def getWords(text):
    return re.compile('\w+').findall(text)

In [35]:
getWords(text1)

['Hello', 'world', 'It', 's', 'time', 'for', 'ROBO', '2', '0']

In [51]:
print(file_counter)

96


In [57]:
print(tensor.shape)

(98, 1000, 3)


In [71]:
dict_tensor = {}
directory = "/Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president"
word_counter = 0 
for file_name in os.listdir(directory):
    with open(directory + "/" + file_name, "r", errors="ignore") as file:
                pos  = 0 
                doc_content = []
                print("Reading %s" %directory + "/" + file_name)
                for line in file:
                    if len(line) > 2:
                        pos += 1
                        doc_content.append(line)
                    if pos == 3:
                        x = ("".join(doc_content))
                        l = (getWords(x))
                        for i in range(0,len(l)):
                            if l[i] not in dict_tensor:
                                word_counter = word_counter +1
                                dict_tensor[l[i]]=word_counter
                            else:
                                continue
                        break 
                        

Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/JC.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/1957-Eisenhower.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/TNK.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/Tmp.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/1881-Garfield.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/1905-Roosevelt.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/1985-Reagan.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/1913-Wilson.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/Cym.txt
Reading /Users/Phaniteja/desktop/RA/Jupyter Notebook Version/shakespeare_president/2Henry4.txt
Reading /Users/Phaniteja/desktop/RA/Ju

In [65]:
print(len(dict_tensor))

3093


In [72]:
print(dict_tensor)

{'Julius': 1, 'Caesar': 2, 'by': 3, 'William': 4, 'Shakespeare': 5, 'Edited': 6, 'Barbara': 7, 'A': 8, 'Mowat': 9, 'and': 10, 'Paul': 11, 'Werstine': 12, 'The': 13, 'Price': 14, 'of': 15, 'Peace': 16, 'Mr': 17, 'Chairman': 18, 'Vice': 19, 'President': 20, 'Chief': 21, 'Justice': 22, 'Speaker': 23, 'members': 24, 'my': 25, 'family': 26, 'friends': 27, 'countrymen': 28, 'the': 29, 'country': 30, 'wherever': 31, 'they': 32, 'may': 33, 'be': 34, 'we': 35, 'meet': 36, 'again': 37, 'as': 38, 'upon': 39, 'a': 40, 'like': 41, 'moment': 42, 'four': 43, 'years': 44, 'ago': 45, 'you': 46, 'have': 47, 'witnessed': 48, 'solemn': 49, 'oath': 50, 'service': 51, 'to': 52, 'I': 53, 'too': 54, 'am': 55, 'witness': 56, 'today': 57, 'testifying': 58, 'in': 59, 'your': 60, 'name': 61, 'principles': 62, 'purposes': 63, 'which': 64, 'people': 65, 'are': 66, 'pledged': 67, 'Two': 68, 'Noble': 69, 'Kinsmen': 70, 'Tempest': 71, 'Fellow': 72, 'Citizens': 73, 'We': 74, 'stand': 75, 'day': 76, 'an': 77, 'eminence'

In [83]:
print(tensor.sum())

15740.0


In [86]:
decompose = KruskalTensor(tensor.shape, rank=3, regularize=1e-6, 
                                  init='nvecs', X_data=tensor)

In [90]:
factors = decompose.U

In [122]:
print(decompose)
print(factors[0])
factors.astype(int)

Tensor("U/0/read:0", shape=(98, 3), dtype=float64)


AttributeError: 'list' object has no attribute 'astype'

In [107]:
clusters = 2
svd = TruncatedSVD(n_components=2, n_iter=20, random_state=42)
reduced = svd.fit_transform(factors)
kmeans = KMeans(n_clusters=clusters, random_state=0).fit(factor_matrix)
labels_predicted = kmeans.labels_
data = [plotly.graph_objs.Scatter(x=[entry[0] for entry in reduced],
                                          y=[entry[1] for entry in reduced],
                                          mode='markers',
                                          marker=dict(color=kmeans.labels_),
                                          text=file_names
                                          )
                ]
fig = go.Figure(data=data)
plotly.offline.plot(fig, filename='kmeans_cluster.html')

ValueError: Expected 2D array, got 1D array instead:
array=[<tensorflow.python.ops.variables.Variable object at 0x1a1c93e940>
 <tensorflow.python.ops.variables.Variable object at 0x1a1c93e320>
 <tensorflow.python.ops.variables.Variable object at 0x1a1c93ef98>].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [101]:
from sklearn.decomposition import TruncatedSVD

In [114]:
fac = factors[1].reshape(-1,1)

AttributeError: 'Variable' object has no attribute 'reshape'

In [123]:
kmeans = KMeans(n_clusters=clusters, random_state=0).fit(factors[0])
labels_predicted = kmeans.labels_

ValueError: setting an array element with a sequence.

In [118]:
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
from sklearn.cluster import KMeans
from sklearn.decomposition import TruncatedSVD
import time
import scipy.cluster.hierarchy
import scipy.spatial.distance
from collections import Counter